### ISSUE TITLE
discussing the code in morning session

### ISSUE THREAD

**Issue by mohamedgamaleldin999999** [Paulinelali/try-bootstrap-with-grace#2]
this is the code review of day 4

**Comment by SaveryIV** [comment]
I don't find any error on the code, seems clean and organized

**Comment by malikhaiderkhan** [comment]
The code is clean and i didn't find any error in the code.

**Comment by Paulinelali** [comment]
Thank you all for your notes. I really appreciate😎

**Comment by mohamedgamaleldin999999** [comment]
the code is perfect only would suggest adding links to hrefs o the navbar links

**Comment by mohamedgamaleldin999999** [comment]
agreed on a perfect code
